USE [master]
GO
/****** Object:  Database [promtest]    Script Date: 27/07/2025 10:58:56 ******/
CREATE DATABASE [promtest]
 CONTAINMENT = NONE
 ON  PRIMARY 
 ---- Cambiar nombre/Ruta del archivo de base de datos
( NAME = N'promtest', FILENAME = N'C:\....\MSSQL\DATA\promtest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0)
 LOG ON 
( NAME = N'promtest_log', FILENAME = N'C:\....\MSSQL\DATA\promtest_log.ldf' , SIZE = 8192KB , MAXSIZE = 1123483648KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [promtest] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [promtest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [promtest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [promtest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [promtest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [promtest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [promtest] SET ARITHABORT OFF 
GO
ALTER DATABASE [promtest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [promtest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [promtest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [promtest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [promtest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [promtest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [promtest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [promtest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [promtest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [promtest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [promtest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [promtest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [promtest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [promtest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [promtest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [promtest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [promtest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [promtest] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [promtest] SET  MULTI_USER 
GO
ALTER DATABASE [promtest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [promtest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [promtest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [promtest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [promtest] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [promtest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [promtest] SET QUERY_STORE = OFF
GO

USE [master]
GO
ALTER DATABASE [promtest] SET  READ_WRITE 
GO
